TICKERS = ["SPY", "QQQ", "TLT", "GLD", "DBC"]
BENCHMARK = "SPY"

START_DATE = "2015-01-01"
END_DATE = None

TARGET_VOLATILITY = 0.10
VOLATILITY_LOOKBACK_DAYS = 20
MAX_EXPOSURE = 1.50
MIN_EXPOSURE = 0.00

ANNUALIZATION_FACTOR = 252
STARTING_INDEX_LEVEL = 100